filebeat.autodiscover:
  providers:
  - type: docker
    labels.dedot: true
    templates:
    - condition:
        contains:
          container.labels.collect_logs_with_filebeat: "true"
      config:
      - type: container
        format: docker
        paths:
        - "/var/lib/docker/containers/${data.docker.container.id}/*.log"

output.logstash:
  hosts: "logstash:5044"