version: "3.2"

services:
  # DISCOVERY SERVICE
  discovery:
    image: my.demo.springboot.microservice.eureka/eureka-service:0.0.1-SNAPSHOT
    deploy:
      replicas: 1
    ports:
      - "8761:8761"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:5000"

  # SERVICES
  account:
    image: my.demo.springboot.microservice.account/account-service:0.0.1-SNAPSHOT
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:5000"
    environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
    - discovery

  todo:
    image: my.demo.springboot.microservice.todo/todo-service:0.0.1-SNAPSHOT
    deploy:
      replicas: 1
    ports:
      - "9090:9090"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:5000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
    - discovery
